base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=chrome
headless=false
explicit.wait=15
api.base.url=https://opensource-demo.orangehrmlive.com/web/index.php
api.validation.enabled=true