name: OrangeHRM Automation Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      environment:
        description: Test environment
        required: true
        default: qa
        type: choice
        options:
          - dev
          - qa
          - prod

      test_suite:
        description: Test suite
        required: true
        default: regression
        type: choice
        options:
          - smoke
          - regression

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: maven

      - name: Run Maven tests
        run: >
          mvn clean test
          -Denv=${{ inputs.environment || 'qa' }}
          -Dcucumber.filter.tags="@${{ inputs.test_suite || 'regression' }}"
        env:
          ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
          ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
          ORANGEHRM_API_BASE_URL: ${{ secrets.ORANGEHRM_API_BASE_URL }}

          ORANGEHRM_API_CLIENT_ID: ${{ secrets.ORANGEHRM_API_CLIENT_ID }}
          ORANGEHRM_API_CLIENT_SECRET: ${{ secrets.ORANGEHRM_API_CLIENT_SECRET }}

          ORANGEHRM_API_REDIRECT_URI: ${{ secrets.ORANGEHRM_API_REDIRECT_URI }}
          ORANGEHRM_API_AUTHORIZATION_CODE: ${{ secrets.ORANGEHRM_API_AUTHORIZATION_CODE }}
          ORANGEHRM_API_VALIDATION_ENABLED: ${{ secrets.ORANGEHRM_API_VALIDATION_ENABLED }}
          ORANGEHRM_ESS_USERNAME: ${{ secrets.ORANGEHRM_ESS_USERNAME }}
          ORANGEHRM_ESS_PASSWORD: ${{ secrets.ORANGEHRM_ESS_PASSWORD }}

      - name: Upload Cucumber reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
          if-no-files-found: ignore

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          if-no-files-found: ignore

      - name: Upload screenshots and test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: target/
          if-no-files-found: ignore